name       : python-ujson
version    : 5.1.0
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/u/ujson/ujson-5.1.0.tar.gz : a88944d2f99db71a3ca0c63d81f37e55b660edde0b07216fb65a3e46403ef004
homepage   : https://github.com/ultrajson/ultrajson
license    : BSD-3-Clausse
component  : programming.python
summary    : Ultra fast JSON decoder and encoder written in C with Python bindings
description: |
    UltraJSON is an ultra fast JSON encoder and decoder written in pure C with bindings for Python 3.7+.
builddeps  :
    - pkgconfig(python3)
    - double-conversion-devel
    - python-pytest
    - python-setuptools-scm
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-double-conversion-from-the-system.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
