name       : python-ujson
version    : 5.4.0
release    : 7
source     :
    - https://files.pythonhosted.org/packages/source/u/ujson/ujson-5.4.0.tar.gz : 6b953e09441e307504130755e5bd6b15850178d591f66292bba4608c4f7f9b00
homepage   : https://github.com/ultrajson/ultrajson
license    : BSD-3-Clausse
component  : programming.python
summary    : Ultra fast JSON decoder and encoder written in C with Python bindings
description: |
    UltraJSON is an ultra fast JSON encoder and decoder written in pure C with bindings for Python 3.7+.
builddeps  :
    - pkgconfig(python3)
    - double-conversion-devel
    - python-pytest
    - python-setuptools-scm
environment: |
    export UJSON_BUILD_DC_INCLUDES="/usr/include/double-conversion"
    export UJSON_BUILD_DC_LIBS="-ldouble-conversion"
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
