name       : python-ujson
version    : 5.3.0
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/u/ujson/ujson-5.3.0.tar.gz : ab938777b3ac0372231ee654a7f6a13787e587b1ca268d8aa7e6fb6846e477d0
homepage   : https://github.com/ultrajson/ultrajson
license    : BSD-3-Clausse
component  : programming.python
summary    : Ultra fast JSON decoder and encoder written in C with Python bindings
description: |
    UltraJSON is an ultra fast JSON encoder and decoder written in pure C with bindings for Python 3.7+.
builddeps  :
    - pkgconfig(python3)
    - double-conversion-devel
    - python-pytest
    - python-setuptools-scm
environment: |
    export UJSON_BUILD_DC_INCLUDES="/usr/include/double-conversion" export UJSON_BUILD_DC_LIBS="-ldouble-conversion"
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
