name       : python-ujson
version    : 3.1.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/u/ujson/ujson-3.1.0.tar.gz : 00bda1de275ed6fe81817902189c75dfd156b4fa29b44dc1f4620775d2f50cf7
homepage   : https://github.com/ultrajson/ultrajson
license    : BSD-3-Clausse
component  : programming.python
summary    : Ultra fast JSON decoder and encoder written in C with Python bindings
description: |
    UltraJSON is an ultra fast JSON encoder and decoder written in pure C with bindings for Python 3.5+.
builddeps  :
    - pkgconfig(python3)
    - double-conversion-devel
    - python-pytest
    - python-setuptools-scm
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-double-conversion-from-the-system.patch
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
